<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GmailToPst.Core\GmailToPst.Core.csproj" />
    <ProjectReference Include="..\GmailToPst.Storage\GmailToPst.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Email" Version="26.7.0" />
    <PackageReference Include="Microsoft.Office.Interop.Outlook" Version="15.0.4797.1004" />
    <PackageReference Include="MsgKit" Version="3.0.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
